# Generated by Django 2.2.6 on 2021-02-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
        ('courses', '0001_initial'),
        ('question_bank', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='question_banks', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='question_banks', to='courses.Quiz'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank', to='themes.Theme', verbose_name='Theme'),
        ),
    ]
