# Generated by Django 2.2.6 on 2021-03-06 15:01

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.generate_filename, verbose_name='Avatar'),
        ),
    ]
