# Generated by Django 2.2.6 on 2021-03-06 15:03

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(upload_to=common.utils.generate_filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=common.utils.generate_filename, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=common.utils.generate_filename, verbose_name='Image'),
        ),
    ]
